-- INSERT DE TIPOS DE TESTS

INSERT INTO razonapro.tests (competence_id, test_id, admin_id, test_name, description, duration_seconds, is_active, questions_to_present, test_mode, created_at)
VALUES
    ('CPE001','TET00001','AMN001','SIMULACRO LECTURA CRITICA I','SIMULACRO OFICIAL MODULO LECTURA CRITICA SABER PRO UFPSO',5400,'Y',20,'EXAM',CURRENT_TIMESTAMP),
    ('CPE001','TET00002','AMN001','PRACTICA LECTURA CRITICA I','PRACTICA LIBRE MODULO LECTURA CRITICA PARA SABER PRO UFPSO',3600,'Y',20,'PRACTICE',CURRENT_TIMESTAMP),
    ('CPE002','TET00003','AMN002','SIMULACRO RAZON CUANTITATIVO I','SIMULACRO OFICIAL MODULO RAZONAMIENTO CUANTITATIVO SABER PRO',5400,'Y',20,'EXAM',CURRENT_TIMESTAMP),
    ('CPE002','TET00004','AMN002','PRACTICA RAZON CUANTITATIVO I','PRACTICA LIBRE MODULO RAZONAMIENTO CUANTITATIVO SABER PRO',3600,'Y',20,'PRACTICE',CURRENT_TIMESTAMP),
    ('CPE003','TET00005','AMN003','SIMULACRO COMP CIUDADANAS I','SIMULACRO OFICIAL MODULO COMPETENCIAS CIUDADANAS SABER PRO',5400,'Y',20,'EXAM',CURRENT_TIMESTAMP),
    ('CPE003','TET00006','AMN003','PRACTICA COMP CIUDADANAS I','PRACTICA LIBRE MODULO COMPETENCIAS CIUDADANAS SABER PRO UFPSO',3600,'Y',20,'PRACTICE',CURRENT_TIMESTAMP),
    ('CPE004','TET00007','AMN004','SIMULACRO COMUNICACION ESCRITA','SIMULACRO OFICIAL MODULO COMUNICACION ESCRITA SABER PRO UFPSO',5400,'Y',20,'EXAM',CURRENT_TIMESTAMP),
    ('CPE004','TET00008','AMN004','PRACTICA COMUNICACION ESCRITA','PRACTICA LIBRE MODULO COMUNICACION ESCRITA PARA SABER PRO',3600,'Y',20,'PRACTICE', CURRENT_TIMESTAMP),
    ('CPE005','TET00009','AMN005','SIMULACRO INGLES I','SIMULACRO OFICIAL MODULO INGLES NIVEL B2 SABER PRO UFPSO',5400,'Y',20,'EXAM',CURRENT_TIMESTAMP),
    ('CPE005','TET00010','AMN005','PRACTICA INGLES I','PRACTICA LIBRE MODULO INGLES PARA SABER PRO UFPSO OCANA',3600,'Y',20,'PRACTICE',CURRENT_TIMESTAMP);

SELECT * FROM razonapro.tests;

-- UPDATE (dispara trg_audi_tests)

UPDATE razonapro.tests
SET duration_seconds = 6000  
WHERE test_id = 'TET00001'
AND competence_id = 'CPE001';

UPDATE razonapro.tests
SET test_mode = 'TIMED'
WHERE test_id = 'TET00003'
AND competence_id = 'CPE002';

UPDATE razonapro.tests
SET is_active = 'N'
WHERE test_id = 'TET00004'
AND competence_id = 'CPE002';

UPDATE razonapro.tests
SET questions_to_present = 15
WHERE test_id = 'TET00009'
AND competence_id = 'CPE005';

UPDATE razonapro.tests
SET description = 'SIMULACRO OFICIAL ACTUALIZADO 2025 MODULO COMPETENCIAS CIUDADANAS'
WHERE test_id = 'TET00005'
AND competence_id = 'CPE003';

SELECT *
FROM razonapro.tests;

SELECT *
FROM razonapro.audi_tests;

-- INSERT Y DELETE
INSERT INTO razonapro.tests (competence_id, test_id, admin_id, test_name, description, duration_seconds, is_active, test_mode, created_at)
VALUES
    ('CPE001','TET00901','AMN001','TEST TEMP 1','TEMPORAL',1800,'N','PRACTICE',CURRENT_TIMESTAMP),
    ('CPE001','TET00902','AMN001','TEST TEMP 2','TEMPORAL',1800,'N','PRACTICE',CURRENT_TIMESTAMP),
    ('CPE001','TET00903','AMN001','TEST TEMP 3','TEMPORAL',1800,'N','PRACTICE',CURRENT_TIMESTAMP),
    ('CPE001','TET00904','AMN001','TEST TEMP 4','TEMPORAL',1800,'N','PRACTICE',CURRENT_TIMESTAMP),
    ('CPE001','TET00905','AMN001','TEST TEMP 5','TEMPORAL',1800,'N','PRACTICE',CURRENT_TIMESTAMP);

DELETE
FROM razonapro.tests
WHERE test_id = 'TET00901'
AND competence_id = 'CPE001';

DELETE
FROM razonapro.tests
WHERE test_id = 'TET00902'
AND competence_id = 'CPE001';

DELETE
FROM razonapro.tests
WHERE test_id = 'TET00903'
AND competence_id = 'CPE001';

DELETE
FROM razonapro.tests
WHERE test_id = 'TET00904'
AND competence_id = 'CPE001';

DELETE
FROM razonapro.tests
WHERE test_id = 'TET00905'
AND competence_id = 'CPE001';

SELECT *
FROM razonapro.audi_tests
ORDER BY row_id DESC;